image: docker:20.10.11
variables:
    DOCKER_TLS_CERTDIR: "/certs"
services:
  - docker:20.10.11-dind

stages:
  - docker_build

build_images:
  stage: docker_build
  variables:
    IMAGE_TAG: 'eu.gcr.io/sourcepole/bbox-qgis-server'
  script:
    # Build
    - |
      if [ -z "$CI_COMMIT_TAG" ]
      then
        docker build -t "$IMAGE_TAG" -f Dockerfile-qgis-server .
      else
        docker build -t "$IMAGE_TAG:latest" -f Dockerfile-qgis-server .
        docker build -t "$IMAGE_TAG:$CI_COMMIT_TAG" -f Dockerfile-qgis-server .
      fi
    # Push
    - echo $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER --password-stdin https://eu.gcr.io
    - |
      if [ -z "$CI_COMMIT_TAG" ]
      then
        docker push "$IMAGE_TAG"
      else
        docker push "$IMAGE_TAG:latest"
        docker push "$IMAGE_TAG:$CI_COMMIT_TAG"
      fi
  only:
    - tags 
    - master
  tags:
    - dockerbuild
