[webserver]
# Web server settings
# Environment variable prefix: BBOX_WEBSERVER__
# server_addr = "127.0.0.1:8080"  # Default: 127.0.0.1:8080
# worker_threads = 4  # Default: number of CPU cores

[[fileserver.static]] 
# Static file serving
# Env var example: BBOX_FILESERVER__STATIC='[{dir="data",path="data"}]'
# ./data/* -> http://localhost:8080/data/
dir = "./data"
path = "data"

[[fileserver.repo]]
# QGIS plugin repository
# Env var example: BBOX_FILESERVER__REPO='[{dir="plugins",path="qgis"}]'
# ./plugins/*.zip -> http://localhost:8080/qgis/plugins.xml
dir = "./plugins"
path = "qgis"

[wmsserver]
# WMS server settings
# Environment variable prefix: BBOX_WMSSERVER__
path = "/wms"                # Base path of WMS endpoints
# num_fcgi_processes = 4     # Default: number of CPU cores
# wait_timeout = 30000       # FCGI wait timeout in ms. Default: 90s
# search_projects = false    # Scan directories and build inventory. Default: true

[wmsserver.qgis_backend]
# QGIS Server settings
# Environment variable prefix: BBOX_WMSSERVER__QGIS_BACKEND__
# project_basedir = "."      # Base dir for project files (.qgs, .qgz)

[wmsserver.umn_backend]
# UMN MapServer settings
# Environment variable prefix: BBOX_WMSSERVER__UMN_BACKEND__
# project_basedir = "."      # Base dir for project files (.map)

#[wmsserver.mock_backend]
# Enable FCGI mockup backend (for testing)
# Environment variable prefix: BBOX_WMSSERVER__MOCK_BACKEND__

[processes.dagster_backend]
# Dagster backend settings
# Environment variable prefix: BBOX_PROCESSES__DAGSTER_BACKEND__
graphql_url = "http://localhost:3000/graphql"
repository_name = "fpds2_processing_repository"
repository_location_name = "fpds2_processing.repos"

[metrics.prometheus]
# Prometheus metrics endpoint
# Environment variable prefix: BBOX_METRICS__PROMETHEUS__
path = "/metrics"

[metrics.jaeger] 
# Jaeger tracing
# Environment variable prefix: BBOX_METRICS__JAEGER__
agent_endpoint = "localhost:6831"
