[webserver]
# Web server settings
# Environment variable prefix: BBOX_WEBSERVER__
# server_addr = "0.0.0.0:8080"  # Default: 127.0.0.1:8080
# worker_threads = 4  # Default: number of CPU cores
# public_server_url = "http://host.docker.internal:8080" # Default: Request address

[metrics.prometheus]
# Prometheus metrics endpoint
# Environment variable prefix: BBOX_METRICS__PROMETHEUS__
path = "/metrics"

#[metrics.jaeger] 
# Jaeger tracing
# Environment variable prefix: BBOX_METRICS__JAEGER__
#agent_endpoint = "localhost:6831"

[[datasource.directory]]
path = "../data"

#[[datasource.postgis]]
#url = "postgresql://t_rex:t_rex@127.0.0.1:5439/t_rex_tests"

[[fileserver.static]] 
# Static file serving
# Env var example: BBOX_FILESERVER__STATIC='[{dir="data",path="data"}]'
# ./data/* -> http://localhost:8080/data/
dir = "./data"
path = "data"

[[fileserver.repo]]
# QGIS plugin repository
# Env var example: BBOX_FILESERVER__REPO='[{dir="plugins",path="qgisrepo"}]'
# ./plugins/*.zip -> http://localhost:8080/qgisrepo/plugins.xml
dir = "./plugins"
path = "qgisrepo"

[wmsserver]
# WMS server settings
# Environment variable prefix: BBOX_WMSSERVER__
# num_fcgi_processes = 4     # Default: number of CPU cores
# wait_timeout = 30000       # FCGI wait timeout in ms. Default: 90s
# search_projects = false    # Scan directories and build inventory

[wmsserver.qgis_backend]
# QGIS Server settings
# Environment variable prefix: BBOX_WMSSERVER__QGIS_BACKEND__
project_basedir = "../data"  # Base dir for project files (.qgs, .qgz)
qgs.path = "/qgis"           # WMS URL base path
qgz.path = "/qgz"            # WMS URL base path

[wmsserver.umn_backend]
# UMN MapServer settings
# Environment variable prefix: BBOX_WMSSERVER__UMN_BACKEND__
project_basedir = "../data"  # Base dir for project files (.map)
path = "/wms/map"            # WMS URL base path

#[wmsserver.mock_backend]
# Enable FCGI mockup backend (for testing)
# Environment variable prefix: BBOX_WMSSERVER__MOCK_BACKEND__
# path = "/wms/mock"

#[processes.dagster_backend]
# Dagster backend settings
# Environment variable prefix: BBOX_PROCESSES__DAGSTER_BACKEND__
#graphql_url = "http://localhost:3000/graphql"
#repository_name = "the_repository"
#repository_location_name = "the.repos"

#[[routing.service]]
#profile = "railway"
#gpkg = "../data/railway-test.gpkg"
#table = "flows"
#geom = "geom"

[grid]
predefined = "web_mercator"

[tile.wms]
baseurl = "http://localhost:8080/qgz/ne_extracts?version=1.3.0"
layers = "ne_extracts"
format = "image/png; mode=8bit"
