[webserver]
# Web server settings
# Environment variable prefix: BBOX_WEBSERVER__
# server_addr = "0.0.0.0:8080"  # Default: 127.0.0.1:8080
# tls_cert = "localhost+1.pem"
# tls_key = "localhost+1-key.pem"
# worker_threads = 4  # Default: number of CPU cores
# public_server_url = "http://host.docker.internal:8080" # Default: Request address

#[auth.oidc]
# OIDC Authentication
# Environment variable prefix: BBOX_AUTH__OIDC__
#client_id = "xxxxxxxxxxxx-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx.apps.googleusercontent.com"
#client_secret = "xxxxxxxxxxxxxxxxxxxxxxxx" # Set with BBOX_AUTH__OIDC__CLIENT_SECRET
#issuer_url = "https://accounts.google.com"

[metrics.prometheus]
# Prometheus metrics endpoint
# Environment variable prefix: BBOX_METRICS__PROMETHEUS__
path = "/metrics"

#[metrics.jaeger] 
# Jaeger tracing
# Environment variable prefix: BBOX_METRICS__JAEGER__
#agent_endpoint = "localhost:6831"

[[datasource.directory]]
dir = "../assets"

#[[datasource.postgis]]
#url = "postgresql://t_rex:t_rex@127.0.0.1:5439/t_rex_tests"

[[assets.static]]
# Static file serving
# Env var example: BBOX_ASSETS__STATIC='[{dir="assets",path="/assets"}]'
# ./assets/* -> http://localhost:8080/assets/
dir = "./assets"
path = "/assets"

[[assets.template]]
# Template file serving
# Env var example: BBOX_ASSETS__TEMPLATE='[{dir="templates",path="/html"}]'
# ./templates/name.html -> http://localhost:8080/html/name/param
dir = "./templates"
path = "/html"

[[assets.repo]]
# QGIS plugin repository
# Env var example: BBOX_ASSETS__REPO='[{dir="plugins",path="/qgisrepo"}]'
# ./plugins/*.zip -> http://localhost:8080/qgisrepo/plugins.xml
dir = "./plugins"
path = "/qgisrepo"

[mapserver]
# Map server settings
# Environment variable prefix: BBOX_MAPSERVER__
# num_fcgi_processes = 4     # Default: number of CPU cores
# wait_timeout = 30000       # FCGI wait timeout in ms. Default: 90s
# search_projects = false    # Scan directories and build inventory

[mapserver.qgis_backend]
# QGIS Server settings
# Environment variable prefix: BBOX_MAPSERVER__QGIS_BACKEND__
project_basedir = "../assets"  # Base dir for project files (.qgs, .qgz)
qgs.path = "/qgis"             # WMS URL base path
qgz.path = "/qgz"              # WMS URL base path

[mapserver.umn_backend]
# UMN MapServer settings
# Environment variable prefix: BBOX_MAPSERVER__UMN_BACKEND__
project_basedir = "../assets"  # Base dir for project files (.map)
path = "/wms/map"              # WMS URL base path

#[mapserver.mock_backend]
# Enable FCGI mockup backend (for testing)
# Environment variable prefix: BBOX_MAPSERVER__MOCK_BACKEND__
# path = "/wms/mock"

#[processes.dagster_backend]
# Dagster backend settings
# Environment variable prefix: BBOX_PROCESSES__DAGSTER_BACKEND__
#graphql_url = "http://localhost:3000/graphql"
#repository_name = "the_repository"
#repository_location_name = "the.repos"

#[[routing.service]]
#profile = "railway"
#gpkg = "../assets/railway-test.gpkg"
#table = "flows"
#geom = "geom"

# -- custom grids --

[[grid]]
json = "../assets/custom-grid-lv95.json"

# -- tile caches --

[[tilecache]]
name = "tilecache"
[tilecache.files]
base_dir = "/tmp/tilecache"

#[[tilecache]]
#name = "aws"
#[tilecache.s3]
#path = "s3://tiles"

# -- tile source provider configuration --

[[tiledatasource]]
name = "t_rex_tests"
#default = true
[tiledatasource.postgis]
url = "postgresql://t_rex:t_rex@127.0.0.1:5439/t_rex_tests"

[[tiledatasource]]
name = "gebco"
[tiledatasource.wms_proxy]
baseurl = "https://www.gebco.net/data_and_products/gebco_web_services/web_map_service/mapserv?version=1.3.0"
format = "image/jpeg"

# -- tile sets --

[[tileset]]
name = "ne_extracts"
wms_project = { project = "ne_extracts", suffix = "qgz", layers = "ne_extracts" }
cache = "tilecache"

[[tileset]]
name = "ne_umn"
wms_project = { project = "ne", suffix = "map", layers = "country", tile_size = 512 }

[[tileset]]
name = "gebco"
wms_proxy = { source = "gebco", layers = "gebco_latest" }

[[tileset]]
name = "rivers_lakes"
tms = "LV95"
[tileset.wms_project]
project = "ne_extracts"
suffix = "qgz"
layers = "ne_10m_lakes,ne_10m_rivers_lake_centerlines"
params = "transparent=true"

[[tileset]]
name = "mbtiles_mvt_fl"
mbtiles = { path = "../assets/liechtenstein.mbtiles" }

#[[tileset]]
#name = "ne_10m_populated_places"
#[tileset.postgis]
#datasource = "t_rex_tests"
#extent = [-179.58998, -90.00000, 179.38330, 82.48332]
#[[tileset.postgis.layer]]
#name = "ne_10m_populated_places"
#table_name = "ne.ne_10m_populated_places"
##geometry_field = "wkb_geometry"
#fid_field = "fid"
#geometry_type = "POINT"
#srid = 3857
#buffer_size = 0
##make_valid = true
#query_limit = 1000
##[[tileset.postgis.layer.query]]
##sql = """SELECT wkb_geometry,fid,scalerank,name,pop_max FROM ne.ne_10m_populated_places"""
