[webserver]
server_addr="0.0.0.0:8080"

[[webserver.static]]
# ./data/* -> http://localhost:8080/data/
dir = "data"
path = "data"

[[webserver.repo]]
# ./plugins/*.zip -> http://localhost:8080/qgis/plugins.xml
dir = "plugins"
path = "qgis"
