[workspace]
members = [
    "bbox-common",
    "bbox-feature-server",
    "bbox-file-server",
    "bbox-map-server",
    "bbox-map-server/mock-fcgi-wms",
    "bbox-map-viewer",
    "bbox-routing-server",
    "bbox-server",
]
default-members = ["bbox-server"]

[patch.crates-io]
fast_paths = { path = "../fast_paths" }
