[workspace]
members = [
    "bbox-common",
    "bbox-feature-server",
    "bbox-file-server",
    "bbox-map-server",
    "bbox-map-server/mock-fcgi-wms",
    "bbox-map-viewer",
    "bbox-processes-server",
    "bbox-routing-server",
    "bbox-server",
    "bbox-tile-server",
]
default-members = ["bbox-server"]

[workspace.dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.57"
log = "0.4.17"
actix-web = "4.0.0"
rust-embed = { version = "5.6.0", features = ["compression"] }
minijinja = { version = "0.17.0", features = ["source"] }
once_cell = "1.12.0"
sqlx = { version = "0.5.11", default-features = false, features = [ "runtime-tokio-native-tls", "sqlite" ] }

#[patch.crates-io]
#fast_paths = { path = "../fast_paths" }
