[package]
name = "bbox-map-server"
version = "0.1.0"
authors = ["Pirmin Kalberer <pka@sourcepole.ch>"]
edition = "2018"

[features]
openapi = []
inventory = []

[dependencies]
bbox-common = { path = "../bbox-common" }
actix-web = { workspace = true }
async-process = "1.0.0"
fastcgi-client = { version = "0.5.0", default-features = false }
bufstream = "0.1.4"
log = { workspace = true }
deadpool = { version = "0.9.2", default-features = false, features = ["managed", "rt_tokio_1"] }
async-trait = "0.1.40"
tokio = { version = "1", features = ["time"] }
opentelemetry = { version = "0.17", default-features = false, features = ["trace", "metrics"] }
prometheus = { version = "0.13", default-features = false }
rand = "0.7.3"
num_cpus = "1.0"
serde = { workspace = true }
serde_json = { workspace = true }
serde-xml-rs = "0.4.0"
awc = "3.0.0-beta.20"
once_cell = { workspace = true }

[dev-dependencies]

[[bin]]
name = "bbox-map-server"
path = "src/main.rs"
