[package]
name = "bbox-routing-server"
version = "0.1.0"
edition = "2021"

[features]
ogcapi = []

[dependencies]
bbox-common = { path = "../bbox-common" }
actix-web = "4.0.0"
fast_paths = { git = "https://github.com/pka/fast_paths", branch="edges-access" }
futures = "0.3.21"
geo = "0.19.0"
geojson = "0.22.3"
geozero = { version = "0.8.0", features = [ "with-gpkg" ] }
rstar = "0.9.2"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.57"
sqlx = { version = "0.5.11", default-features = false, features = [ "runtime-tokio-native-tls", "sqlite" ] }

[[bin]]
name = "bbox-routing-server"
path = "src/main.rs"
