[package]
name = "bbox-feature-server"
version = "0.1.0"
authors = ["Pirmin Kalberer <pka@sourcepole.ch>"]
edition = "2018"

[dependencies]
bbox-common = { path = "../bbox-common" }
actix-web = "3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.57"
json = "0.12"

[dev-dependencies]
actix-rt = "2.3.0"
