[package]
name = "bbox-feature-server"
version = "0.1.0"
authors = ["Pirmin Kalberer <pka@sourcepole.ch>"]
edition = "2018"

[dependencies]
actix-web = "3"

env_logger = "0.7"

serde = "1.0.116"
serde_json = "1.0.57"
json = "0.12"

dotenv = "0.15.0"
config = { version = "0.10.1", default-features = false }

[dev-dependencies]
actix-rt = "2.3.0"
