[package]
name = "bbox-feature-server"
version = "0.1.0"
authors = ["Pirmin Kalberer <pka@sourcepole.ch>"]
edition = "2018"

[features]
ogcapi = []

[dependencies]
bbox-common = { path = "../bbox-common" }
actix-web = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
log = { workspace = true }
rust-embed = { workspace = true }
minijinja = { workspace = true }
once_cell = { workspace = true }

[[bin]]
name = "bbox-feature-server"
path = "src/main.rs"
