[package]
name = "bbox-feature-server"
version = "0.1.0"
authors = ["Pirmin Kalberer <pka@sourcepole.ch>"]
edition = "2018"

[features]
ogcapi = []

[dependencies]
bbox-common = { path = "../bbox-common" }
actix-web = "4.0.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.57"
log = "0.4.17"
rust-embed = { version = "5.6.0", features = ["compression"] }
minijinja = { version = "0.17.0", features = ["source"] }
once_cell = "1.12.0"

[[bin]]
name = "bbox-feature-server"
path = "src/main.rs"
