[package]
name = "bbox-feature-server"
version = "0.1.0"
authors = ["Pirmin Kalberer <pka@sourcepole.ch>"]
edition = "2018"

[features]
openapi = []

[dependencies]
bbox-common = { path = "../bbox-common" }
actix-web = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
log = { workspace = true }
rust-embed = { workspace = true }
minijinja = { workspace = true }
once_cell = { workspace = true }
geozero = { workspace = true, features = [ "with-gpkg", "with-postgis-sqlx" ] }
sqlx = { workspace = true }
futures = { workspace = true }
async-trait = "0.1.65"

[dev-dependencies]
tokio = { workspace = true, features = ["full"] }

[[bin]]
name = "bbox-feature-server"
path = "src/main.rs"
