global:
  scrape_interval: 2s
  evaluation_interval: 2s

scrape_configs:
  - job_name: "grafana"
    scrape_interval: 5s
    static_configs:
      - targets:
          - grafana:3000
  - job_name: "prometheus"
    scrape_interval: 5s
    static_configs:
      - targets:
          - localhost:9090
  - job_name: "wmsapi"
    scrape_interval: 5s
    static_configs:
      - targets:
          - 172.17.0.1:8080
