[webserver]
loglevel = "Warn"

[[datasource]]
name = "pg"
[datasource.postgis]
#url = "postgresql://mvtbench:mvtbench@mvtbenchdb/mvtbench"
url = "postgresql://mvtbench:mvtbench@127.0.0.1:5439/mvtbench"

[[tileset]]
name = "ne_countries"
# No tile cache for HTTP tile server testing. Enabled for seeding tests via CLI options.
[[tileset.tms]]
id = "WebMercatorQuad"
minzoom = 0
maxzoom = 6
[tileset.postgis]
attribution = "Natural Earth v4"
postgis2 = false
[tileset.postgis.extent]
minx = -179.97277
miny = -83.05457
maxx = 179.99366
maxy = 83.23559

#[tileset.postgis.diagnostics]
#reference_size = 800_000

[[tileset.postgis.layer]]
name = "country"
geometry_field = "wkb_geometry"
geometry_type = "MULTIPOLYGON"
# simplify = true
# tolerance = "!pixel_width!/2"
buffer_size = 3

[[tileset.postgis.layer.query]]
minzoom = 0
sql = "SELECT wkb_geometry, adm0_a3, mapcolor7 FROM ne_10m_admin_0_countries WHERE min_zoom::integer <= !zoom!"

[[tileset.postgis.layer]]
name = "country-name"
geometry_field = "wkb_geometry"
geometry_type = "POINT"
buffer_size = 0

[[tileset.postgis.layer.query]]
minzoom = 0
sql = "SELECT wkb_geometry, abbrev, name FROM ne_10m_admin_0_country_points"

[[tileset.postgis.layer]]
name = "geo-lines"
geometry_field = "wkb_geometry"
geometry_type = "MULTILINESTRING"
buffer_size = 0

[[tileset.postgis.layer.query]]
minzoom = 1
maxzoom = 4
sql = "SELECT wkb_geometry, name FROM ne_50m_geographic_lines"

[[tileset.postgis.layer.query]]
minzoom = 5
sql = "SELECT wkb_geometry, name FROM ne_10m_geographic_lines"

[[tileset.postgis.layer]]
name = "land-border-country"
geometry_field = "wkb_geometry"
geometry_type = "MULTILINESTRING"
fid_field = "ogc_fid"
# simplify = true
# tolerance = "!pixel_width!/2"
buffer_size = 0

[[tileset.postgis.layer.query]]
minzoom = 0
sql = "SELECT wkb_geometry FROM ne_10m_admin_0_boundary_lines_land WHERE min_zoom::integer <= !zoom!"

[[tileset.postgis.layer]]
name = "state"
geometry_field = "wkb_geometry"
geometry_type = "MULTILINESTRING"
# simplify = true
# tolerance = "!pixel_width!/2"
buffer_size = 0

[[tileset.postgis.layer.query]]
minzoom = 0
sql = "SELECT wkb_geometry, adm0_a3 FROM ne_10m_admin_1_states_provinces_lines WHERE min_zoom::integer <= !zoom!"
