[package]
name = "bbox-tile-server"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = { workspace = true }
anyhow = "1.0.52"
async-channel = "1.6.1"
async-trait = "0.1.56"
bbox-common = { path = "../bbox-common" }
bytes = "1.1.0"
clap = { workspace = true }
crossbeam = "0.8.1"
dyn-clone = "1.0.6"
futures = "0.3"
futures-util = "0.3.21"
indicatif = "0.16.2"
log = { workspace = true }
num_cpus = { workspace = true }
reqwest = "0.11.11"
rusoto_core = "0.47.0"
rusoto_s3 = "0.47.0"
serde = { workspace = true }
tempfile = "3.3.0"
thiserror = { workspace = true }
tile-grid = { git = "https://github.com/pka/tile-grid.git" }
tokio = { version = "1.17.0", features = ["rt-multi-thread", "fs", "sync"] }

[[bin]]
name = "bbox-tile-server"
path = "src/main.rs"
