[package]
name = "bbox-tile-server"
version = "0.1.0"
edition = "2021"

[features]
openapi = []

[dependencies]
bbox-common = { path = "../bbox-common" }
clap = { version = "4.2.1", features = ["derive"] }
actix-web = { workspace = true }
rusoto_core = "0.47.0"
rusoto_s3 = "0.47.0"
futures = "0.3"
num_cpus = "1.13.1"
tokio = { version = "1.17.0", features = ["rt-multi-thread", "fs", "sync"] }
futures-util = "0.3.21"
crossbeam = "0.8.1"
reqwest = "0.11.11"
bytes = "1.1.0"
tile-grid = "0.3.0"
log = { workspace = true }
indicatif = "0.16.2"
serde = { workspace = true }
async-trait = "0.1.56"
dyn-clone = "1.0.6"
async-channel = "1.6.1"
tempfile = "3.3.0"
thiserror = { workspace = true }
anyhow = "1.0.52"

[[bin]]
name = "bbox-tile-server"
path = "src/main.rs"
