[package]
name = "bbox-tile-server"
version = "0.1.0"
edition = "2021"

[features]
default = ["map-server", "asset-server"]
map-server = ["bbox-map-server"]
asset-server = ["bbox-asset-server"]
# wms-proxy = ["reqwest"]
# s3 = ["rusoto_core", "rusoto_s3"]
projtransform = ["tile-grid/projtransform"]

[dependencies]
actix-web = { workspace = true }
anyhow = "1.0.52"
async-channel = "1.6.1"
async-trait = { workspace = true }
bbox-core = { path = "../bbox-core" }
bbox-asset-server = { path = "../bbox-asset-server", optional = true }
bbox-map-server = { path = "../bbox-map-server", optional = true }
bytes = "1.1.0"
clap = { workspace = true }
crossbeam = "0.8.1"
dyn-clone = "1.0.6"
futures = "0.3"
futures-util = "0.3.21"
indicatif = "0.16.2"
log = { workspace = true }
martin-mbtiles = { version = "0.2.1", default-features = false, features = ["rustls"], git = "https://github.com/pka/martin", branch = "sqlx-rustls" }
num_cpus = { workspace = true }
prometheus = { workspace = true }
reqwest = { workspace = true }
rusoto_core = { version = "0.47.0", default-features = false, features = ["rustls"] }
rusoto_s3 = { version = "0.47.0", default-features = false, features = ["rustls"] }
serde = { workspace = true }
serde_json = { workspace = true }
tempfile = "3.3.0"
thiserror = { workspace = true }
tile-grid = "0.5.2"
tilejson = "0.3.2"
tokio = { version = "1.17.0", features = ["rt-multi-thread", "fs", "sync"] }

[[bin]]
name = "bbox-tile-server"
path = "src/main.rs"
