[webserver]
server_addr = "0.0.0.0:8080"
worker_threads = 32

[mapserver]
path = "/wms"
num_fcgi_processes = 32
search_projects = false

[mapserver.mock_backend]
# Enable FCGI mockup backend (for testing)

[metrics.prometheus]
path = "/metrics"

[metrics.jaeger] 
agent_endpoint = "localhost:6831"
