[webserver]
server_addr = "0.0.0.0:8080"
worker_threads = 32

[mapserver]
num_fcgi_processes = 32
search_projects = false

[mapserver.mock_backend]
# Enable FCGI mockup backend (for testing)
# Environment variable prefix: BBOX_MAPSERVER__MOCK_BACKEND__
path = "/wms/mock"

[metrics.prometheus]
path = "/metrics"

[metrics.jaeger] 
agent_endpoint = "localhost:6831"
