global:
  scrape_interval: 2s
  evaluation_interval: 2s

scrape_configs:
  - job_name: "grafana"
    scrape_interval: 5s
    static_configs:
      - targets:
          - grafana:3000
  - job_name: "prometheus"
    scrape_interval: 5s
    static_configs:
      - targets:
          - localhost:9090
  - job_name: "bbox"
    scrape_interval: 5s
    static_configs:
      - targets:
          - bbox:8080
  - job_name: "authentik_server"
    scrape_interval: 10s
    static_configs:
      - targets:
          - authentik_server:9300
  - job_name: "windmill"
    scrape_interval: 5s
    static_configs:
      - targets:
          - windmill:8001
  - job_name: "windmill_worker"
    scrape_interval: 5s
    static_configs:
      - targets:
          - windmill_worker:8001
