[package]
name = "bbox-file-server"
version = "0.1.0"
edition = "2021"

[dependencies]
bbox-common = { path = "../bbox-common" }
actix-web = "3"
actix-files = "0.5.0"
serde = { version = "1.0", features = ["derive"] }
log = "0.4.14"
