version: '3'

services:
  postgresql:
    image: postgis/postgis:15-3.3
    # restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./create-multiple-postgresql-databases.sh:/docker-entrypoint-initdb.d/20_create_dbs.sh:ro
      - ./init-windmill-as-superuser.sql:/docker-entrypoint-initdb.d/init-windmill-as-superuser.sql:ro
    # ports:
      # - 5432:5432
    environment:
      POSTGRES_DB: $POSTGIS_DB
      POSTGRES_PASSWORD: ${PG_PASS}
      POSTGRES_MULTIPLE_DATABASES: $POSTGRES_MULTIPLE_DATABASES
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -p 5432" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres-data:
    driver: local

networks:
  default:
    name: bbox
