version: '3'

services:
  nginx:
    image: nginx:1.23
    ports:
      - "8080:8080"
      - "127.0.0.1:9000:9000"
      - "127.0.0.1:8000:8000"
       #- "443:443"
    volumes:
      - ./nginx:/etc/nginx/templates:ro

networks:
  default:
    name: bbox
    external: true
