[package]
name = "bbox-common"
version = "0.1.0"
edition = "2021"

[dependencies]
env_logger = "0.9.0"
figment = { version = "0.10.6", features = ["env", "toml"] }
once_cell = "1.8.0"
ignore = "0.4"
minijinja = { version = "0.8.2", features = ["source"] }

[dev-dependencies]
serde = { version = "1.0", features = ["derive"] }
