[package]
name = "bbox-processes-server"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-files = "0.6.0"
actix-web = { workspace = true }
async-trait = { workspace = true }
awc = "3.0.0"
bbox-common = { path = "../bbox-common" }
chrono = { version = "0.4", features = ["serde"] }
clap = { workspace = true }
log = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
swagger = { version = "6.1", features = ["serdejson"] }
thiserror = { workspace = true }
tokio = { version = "1", features = ["time"] }

[[bin]]
name = "bbox-processes-server"
path = "src/main.rs"
