[package]
name = "bbox-processes-server"
version = "0.1.0"
edition = "2021"

[features]
openapi = []

[dependencies]
bbox-common = { path = "../bbox-common" }
actix-web = { workspace = true }
actix-files = "0.6.0"
serde = { workspace = true }
serde_json = { workspace = true }
awc = "3.0.0"
swagger = { version = "6.1", features = ["serdejson"] }
chrono = { version = "0.4", features = ["serde"] }
thiserror = "1.0.31"
log = { workspace = true }
tokio = { version = "1", features = ["time"] }

[[bin]]
name = "bbox-processes-server"
path = "src/main.rs"
