[package]
name = "bbox-processes-server"
version = "0.1.0"
edition = "2021"

[dependencies]
bbox-common = { path = "../bbox-common" }
actix-web = "4.0.0"
actix-files = "0.6.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.57"
utoipa = { version = "0.2.0", features = ["actix_extras"] }
awc = "3.0.0"
swagger = { version = "6.1", features = ["serdejson"] }
chrono = { version = "0.4", features = ["serde"] }
thiserror = "1.0.31"
log = "0.4.17"
tokio = { version = "1", features = ["time"] }

[[bin]]
name = "bbox-processes-server"
path = "src/main.rs"
