[package]
name = "bbox-server"
version = "0.1.0"
edition = "2021"

[features]
default = ["file-server"]
map-server = ["bbox-map-server"]
file-server = ["bbox-file-server"]
feature-server = ["bbox-feature-server"]
map-viewer = ["bbox-map-viewer"]

[dependencies]
bbox-common = { path = "../bbox-common" }
bbox-feature-server = { path = "../bbox-feature-server", optional = true }
bbox-file-server = { path = "../bbox-file-server", optional = true }
bbox-map-viewer = { path = "../bbox-map-viewer", optional = true }
bbox-map-server = { path = "../bbox-map-server", optional = true }
actix-web = "3"
actix-service = "1"
actix-web-prom = "0.5.0"
opentelemetry = { version = "0.9", default-features = false, features = ["trace"] }
opentelemetry-jaeger = { version = "0.8.0", features = ["collector_client"] }
num_cpus = "1.0"
serde = { version = "1.0", features = ["derive"] }
