[package]
name = "bbox-server"
version = "0.1.0"
edition = "2018"

[features]
default = ["file-server"]
map-server = ["bbox-map-server"]
file-server = ["bbox-file-server"]
feature-server = ["bbox-feature-server"]
map-viewer = ["bbox-map-viewer", "bbox-map-server/inventory"]
processes-server = ["bbox-processes-server"]
routing-server = ["bbox-routing-server"]

[dependencies]
actix-service = "2.0.2"
actix-web = { workspace = true }
bbox-common = { path = "../bbox-common" }
bbox-feature-server = { path = "../bbox-feature-server", features=["html"], optional = true }
bbox-file-server = { path = "../bbox-file-server", optional = true }
bbox-map-server = { path = "../bbox-map-server", optional = true }
bbox-map-viewer = { path = "../bbox-map-viewer", optional = true }
bbox-processes-server = { path = "../bbox-processes-server", optional = true }
bbox-routing-server = { path = "../bbox-routing-server", optional = true }
clap = { workspace = true }
minijinja = { workspace = true }
once_cell = { workspace = true }
rust-embed = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }

[[bin]]
name = "bbox-server"
path = "src/main.rs"
