[package]
name = "bbox-server"
version = "0.1.0"
edition = "2018"

[features]
default = ["file-server"]
map-server = ["bbox-map-server"]
file-server = ["bbox-file-server"]
feature-server = ["bbox-feature-server"]
map-viewer = ["bbox-map-viewer", "bbox-map-server/inventory"]
processes-server = ["bbox-processes-server"]
routing-server = ["bbox-routing-server"]

[dependencies]
bbox-common = { path = "../bbox-common" }
bbox-feature-server = { path = "../bbox-feature-server", features=["ogcapi"], optional = true }
bbox-file-server = { path = "../bbox-file-server", optional = true }
bbox-map-viewer = { path = "../bbox-map-viewer", optional = true }
bbox-map-server = { path = "../bbox-map-server", optional = true }
bbox-processes-server = { path = "../bbox-processes-server", features=["ogcapi"], optional = true }
bbox-routing-server = { path = "../bbox-routing-server", features=["ogcapi"], optional = true }
actix-web = { workspace = true }
actix-service = "2.0.2"
actix-web-opentelemetry = { version = "0.12", features = ["metrics"] }
opentelemetry = { version = "0.17", default-features = false, features = ["trace", "metrics", "rt-tokio"] }
opentelemetry-prometheus = { version = "0.10" }
opentelemetry-jaeger = { version = "0.16", features = ["rt-tokio"] }
num_cpus = "1.0"
rust-embed = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
minijinja = { workspace = true }
once_cell = { workspace = true }
clap = { version = "3.1.18", features = ["derive"] }

[[bin]]
name = "bbox-server"
path = "src/main.rs"
