[book]
authors = ["BBOX contributors"]
language = "en"
multilingual = false
src = "src"
title = "BBOX Server Documentation"

[build]
build-dir = "../target/book"

[output.html]
curly-quotes = true
git-repository-url = "https://github.com/sourcepole/bbox"
edit-url-template = "https://github.com/sourcepole/bbox/edit/main/docs/{path}"
